In [1]:
from keras.datasets import mnist

(X_train, y_train),(X_test, y_test) = mnist.load_data() 

Using TensorFlow backend.


In [2]:
import matplotlib.pyplot as plt
plt.imshow(X_train[0])

In [3]:
plt.show()

In [5]:
X_train[0].shape

(28, 28)

In [6]:
X_train = X_train.reshape(60000, 28,28,1)
X_test = X_test.reshape(10000, 28,28,1)

In [8]:
from keras.utils import to_categorical

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [9]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [10]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten

model = Sequential()

model.add(Conv2D(64, kernel_size = 3, activation = 'relu', input_shape = (28,28,1)))
model.add(Conv2D(32, kernel_size = 3, activation = 'relu'))
model.add(Flatten())
model.add(Dense(10, activation = 'softmax'))

Instructions for updating:
Colocations handled automatically by placer.


In [11]:
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [12]:
model.fit(X_train, y_train, validation_data = (X_test, y_test), epochs = 3)

Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/3
60000/60000 [==============================] - 182s 3ms/step - loss: 1.3600 - acc: 0.8855 - val_loss: 0.0980 - val_acc: 0.9707
Epoch 2/3
60000/60000 [==============================] - 177s 3ms/step - loss: 0.0706 - acc: 0.9789 - val_loss: 0.0819 - val_acc: 0.9755
Epoch 3/3
60000/60000 [==============================] - 179s 3ms/step - loss: 0.0492 - acc: 0.9849 - val_loss: 0.0770 - val_acc: 0.9797


In [13]:
model.predict(X_test[:4])

array([[9.9893391e-08, 6.0215929e-12, 2.0661148e-06, 2.6425670e-07,
        5.4669256e-15, 4.7227462e-11, 1.0279507e-13, 9.9999738e-01,
        1.2072920e-07, 1.0357040e-07],
       [8.5608926e-10, 3.4625441e-06, 9.9999654e-01, 3.7972537e-12,
        3.8821828e-12, 4.6489684e-13, 2.4887603e-09, 1.4520594e-14,
        1.3007307e-08, 1.7489257e-16],
       [2.1187047e-06, 9.9945205e-01, 4.2848309e-04, 1.2075656e-06,
        1.1669570e-05, 1.7796669e-05, 1.9962024e-05, 4.2922809e-05,
        2.3421138e-05, 3.9200395e-07],
       [9.9999368e-01, 3.5214085e-11, 1.8213579e-07, 5.1578414e-10,
        5.6756797e-11, 2.1843697e-08, 5.8477121e-06, 1.7068759e-09,
        4.5361659e-08, 2.1411797e-07]], dtype=float32)

In [14]:
y_test[:4]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)